### ISSUE TITLE
今日头条互娱研发上海HR Sunny问候函

### ISSUE THREAD

**Issue by flysunnyDW** [cainmagi/FFmpeg-Encoder-Decoder-for-Python#2]
好，我是今日头条互娱研发上海HR Sunny，有幸看到您的音视频相关项目分享，希望有机会和您认识，不知道是否方便加个微信沟通，我的微信是fengzhigu-s，期待您的回复。

**Comment by cainmagi** [comment]
您好，抱歉我在如此之久以后才联系您！大概是早期版本的Github没有提供提醒功能的缘故，我在很长时间内都没有注意到这个项目的issues。

这个项目是我刚入学的时候，开发的一个实验性的项目。本来只是为了内部使用开发的，所以在很多地方的实现没有做到非常清晰、可靠。这也是我迟迟没有维护此项目、为其撰写文档的原因。最近因为相关项目的收尾，我才重新把这个项目整理好。

我目前仍然是一名学生，暂时没有任何商业合作的能力、和意向。即使未来还会持续开发，本项目也会从始至终一直是免费、开源、自由的软件，我不打算让它涉入任何商业成分。参见

https://cainmagi.github.io/FFmpeg-Encoder-Decoder-for-Python/zh-cn/docs/troubleshooting/qna/#commercial-plan

关于这一点，我很抱歉。我并不方便和您进行深入交流。因此，我决定将这个issue关闭。

感谢您关注这个项目！
